# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[28,)" #mandatory (28 is current forge version)
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="vmt" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="${file.jarVersion}" #mandatory
 # A display name for the mod
displayName="Villager Memory Tweaks" #mandatory
displayURL="http://acro.rf.gd/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="vmt.png" #optional
# A text field displayed in the mod UI
credits="Cadiboo and VSNGamer for having understandable code" #optional
# A text field displayed in the mod UI
authors="Acro" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
A mod that dynamically assigns villagers jobs so more of the village can be utilised, also helps them find the gathering point

'''

